// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SWPPDbContext))]
    [Migration("20220505180701_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend.Models.BankingInfo", b =>
                {
                    b.Property<Guid>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankId");

                    b.ToTable("BankingInfos");

                    b.HasData(
                        new
                        {
                            BankId = new Guid("40822906-84f0-4dae-b8f0-696fce457db8"),
                            BankLocation = "Dong Da, Ha Noi, Ngan Hang co phan quan doi MB Bank, Merchant",
                            ProfileNumber = "7467811997849"
                        },
                        new
                        {
                            BankId = new Guid("dbe552e4-37de-4ffb-b920-ab7caa9ebe0d"),
                            BankLocation = "Dong Da, Ha Noi, Ngan Hang co phan quan doi MB Bank, Client",
                            ProfileNumber = "1255070770448"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
